Merged 'master' into 'main' with unrelated histories

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,16 +27,16 @@ jobs:
 
       - name: 🔨 Install Dependencies and Build
         run: |
-          mkdir -p build-output  # Create a folder to store the build output
+          mkdir -p build-output
           npm install --force
           npm install axios --save
           npm run build
-          mv build/* build-output/  # Move the build output to the new folder
+          mv build/* build-output/
         env:
           CI: false
 
       - name: Verify Build Output
-        run: ls -la build-output  # Verify the contents of the build-output folder
+        run: ls -la build-output
 
       - name: 📂 Deploy to Server via SSH
         uses: appleboy/ssh-action@v0.1.3
@@ -46,8 +46,21 @@ jobs:
           key: ${{ secrets.SERVER_SSH_KEY }}
           port: 22
           script: |
+            # Navigate to the project directory on the server and pull the latest code
+            cd /var/www/admin.lovebird4u.com/code || exit 1
+            git pull || exit 1
+            
+            # Install dependencies and build the project on the server
+            npm install || exit 1
+            npm run build || exit 1
+            
+            # Clean up old files (except 'DatingAppFlutter-Backend' directory)
             cd /var/www/admin.lovebird4u.com || exit 1
             find . -maxdepth 1 ! -name 'DatingAppFlutter-Backend' ! -name '.' -exec rm -rf {} + || exit 1
-            scp -r ./build-output/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/admin.lovebird4u.com || exit 1
+            
+            # Deploy new files
+            rsync -avz --delete build-output/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/admin.lovebird4u.com/ || exit 1
+            
+            # Restart and save PM2 process list
             pm2 restart lovebird-admin-site || exit 1
             pm2 save || exit 1
